services:
  qdrant:
    image: qdrant/qdrant:latest
    restart: always
    container_name: qdrant
    ports:
      - 6333:6333
      - 6334:6334
    expose:
      - 6333
      - 6334
      - 6335
    environment:
      - QDRANT_LOG_LEVEL=INFO
    volumes:
      - ./qdrant_data:/qdrant/storage
    
  data_loader:
    build:
      context: .
      dockerfile: Dockerfile.loader
    volumes:
      - ./data_loader.py:/app/data_loader.py
      - ./.env:/app/.env
      - ./data:/data