FROM python:3.9-slim

WORKDIR /app

COPY data_loader.py /app/data_loader.py

# Install necessary packages
COPY requirements.txt /opt/app/requirements.txt
WORKDIR /opt/app
RUN python -m pip install --upgrade pip setuptools
RUN pip install --no-cache-dir -r requirements.txt

# For monitoring and debugging
RUN apt-get update && apt-get install -y curl

# Set Qdrant client to use higher timeout
ENV QDRANT_TIMEOUT=300

# Entry point will be the Python script mounted from the host
CMD ["python", "/app/data_loader.py"]